SELECT FKICKER, (SUM(SUCCESS) / COUNT(*) * 100) AS SUCCESS_PERCENTAGE, 
 SUM(SUCCESS) SUCCESS_COUNT, SUM(HIGH_PRESSURE) AS HIGH_PRESSURE_COUNT,
 SUM(BLOCKED) AS BLOCKED_COUNT,COUNT(*) AS COUNT,
 (SELECT COUNT(*) FROM db_nfl.PENALTY WHERE pen = FKICKER
  GROUP BY pen) AS PENALITY_COUNT,
  pos1,pos2,height,weight,dob,forty,bench,vertical,broad,shuttle,cone,arm,hand,dpos,start,jnum,dcp,nflid
 FROM (
		SELECT FGXP, PBP.GID, PBP.FKICKER, PNAME AS KICKER_NAME, DIST, QTR, MIN, TIMO AS TIMO_REMAIN,
		CASE WHEN GOOD = 'Y' THEN 1 ELSE 0 END AS SUCCESS,
		CASE WHEN DETAIL LIKE '%BLOCKED%' THEN 1 ELSE 0 END AS BLOCKED,
		CASE WHEN DPOS = 0 THEN 'UNDRAFTED' ELSE DPOS END AS DRAFT_POSITION,
		DIST - (100 - CASE WHEN YFOG = '' THEN '98' ELSE YFOG END) AS YDS_BEHIND_LOS,
		PTSO - PTSD AS POINT_DIFFERENTIAL,
		CASE WHEN QTR IN ('2' , '4') AND MIN <= 2 AND (PTSO - PTSD) >= - 3 THEN 1 ELSE 0 END AS HIGH_PRESSURE,
		TEMP, HUMD, WSPD, WDIR, COND, SURF, DETAIL
		FROM PBP
		LEFT OUTER JOIN PLAYER PLAYER ON PBP.FKICKER = PLAYER.PLAYER
		LEFT OUTER JOIN GAME ON PBP.GID = GAME.GID
		WHERE TYPE = 'FGXP')
 AS KICKER
 LEFT OUTER JOIN PLAYER PLAYER ON KICKER.FKICKER = PLAYER.PLAYER
 GROUP BY FKICKER 
 ORDER BY SUCCESS_COUNT DESC
